name: vetdose
description: "A new Flutter project."
# Prevent the package from being accidentally published to pub.dev.
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.19
  chewie: ^1.8.5

  # Cupertino Icons for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  expressions: ^0.2.5+2
  math_expressions: ^2.1.1
  animations: ^2.0.7
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.3
  pdf: ^3.10.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/test.png
    - assets/splash_logo.gif
    - assets/vetdose_logo.png
    - assets/cat.png
    - assets/dog.png

