// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTWWkxvWtgLv1mEtAF0ApHwN7w6J1Gkb8',
    appId: '1:350083664838:web:cdaea667c1f40563c300c7',
    messagingSenderId: '350083664838',
    projectId: 'vetdose-a1b75',
    authDomain: 'vetdose-a1b75.firebaseapp.com',
    storageBucket: 'vetdose-a1b75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGMNhY3Ngi-W5-WH9sYc770HvpzEfuFbA',
    appId: '1:350083664838:android:3481c8f26e07d868c300c7',
    messagingSenderId: '350083664838',
    projectId: 'vetdose-a1b75',
    storageBucket: 'vetdose-a1b75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH0XNm93viaCw9ZEOY45fhy9sfjwjKfNY',
    appId: '1:350083664838:ios:a6d996b0c319c8e9c300c7',
    messagingSenderId: '350083664838',
    projectId: 'vetdose-a1b75',
    storageBucket: 'vetdose-a1b75.appspot.com',
    iosBundleId: 'com.example.vetdose',
  );
}
